# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1c2de7dc668c536d60a76dac5accc2f4036b7a03bbb1d2a95a818657151811fb0a4cbc586d8c09dedd2dff9c588855fe4d85bb4597880bef99caa67705e7c75

test:
  secret_key_base: 8fb7dea2045ef717b0f273d814217451532884f240cc0aaa91d66a5e9f6838a74ec520d534b69d8a80d1ffd0159a8a732c8dbba9b70dd21500e645c00db3e4d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
